//! Digest source inventory for Memory OS.
//!
//! Daily email, Slack, AI, SWE, and notes digests can be valuable memory
//! evidence, but they are sensitive and noisy. This module only inventories
//! digest-like source files and classifies operational artifacts. It does not
//! read digest contents or promote facts into active memory.

use crate::error::{IndexError, IndexResult};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use time::OffsetDateTime;

const DIGEST_REVIEW_MARKER: &str = "<!-- engram:generated:file digest-review-v1 -->";

/// Stateless service for digest source discovery.
#[derive(Debug, Default, Clone)]
pub struct DigestService;

impl DigestService {
    /// Create a digest service.
    #[must_use]
    pub fn new() -> Self {
        Self
    }

    /// Inventory digest-like files under a root path.
    ///
    /// This is intentionally read-light: only filesystem metadata and path names
    /// are inspected. File contents are not read.
    pub fn inventory(&self, options: DigestInventoryOptions) -> IndexResult<DigestInventory> {
        inventory_digest_sources(options)
    }

    /// Export a generated review batch for digest source candidates.
    ///
    /// The export writes metadata-only review pages. It does not read digest file
    /// contents or write Memory OS records.
    pub fn export_review_batch(
        &self,
        output_path: impl AsRef<Path>,
        options: DigestInventoryOptions,
    ) -> IndexResult<DigestReviewExport> {
        export_digest_review_batch(output_path.as_ref(), options)
    }
}

/// Options for digest source inventory.
#[derive(Debug, Clone)]
pub struct DigestInventoryOptions {
    /// Root directory to scan.
    pub root_path: PathBuf,
    /// Maximum included candidates to return.
    pub limit: Option<usize>,
    /// Include files that are normally treated as operational artifacts.
    pub include_operational: bool,
}

impl DigestInventoryOptions {
    /// Create inventory options.
    #[must_use]
    pub fn new(root_path: impl Into<PathBuf>) -> Self {
        Self {
            root_path: root_path.into(),
            limit: None,
            include_operational: false,
        }
    }
}

/// Digest source inventory result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DigestInventory {
    /// Inventory timestamp.
    #[serde(with = "time::serde::rfc3339")]
    pub generated_at: OffsetDateTime,
    /// Root path scanned.
    pub root_path: String,
    /// Files encountered under digest-like paths.
    pub files_scanned: usize,
    /// Total candidate digest files found before truncation.
    pub total_candidates: usize,
    /// Returned candidate count after limit.
    pub returned_candidates: usize,
    /// Whether candidate output was truncated by limit.
    pub truncated: bool,
    /// Excluded file count.
    pub excluded_count: usize,
    /// Candidate counts by digest source kind.
    pub by_source_kind: BTreeMap<String, usize>,
    /// Candidate counts by file format.
    pub by_format: BTreeMap<String, usize>,
    /// Candidate counts by collection directory.
    pub by_collection: BTreeMap<String, usize>,
    /// Candidate digest files.
    pub candidates: Vec<DigestSourceCandidate>,
    /// Excluded digest-adjacent files.
    pub exclusions: Vec<DigestExcludedPath>,
    /// Operator warnings.
    pub warnings: Vec<String>,
}

/// Generated digest review batch export.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DigestReviewExport {
    /// Output directory for review files.
    pub output_path: String,
    /// Inventory used to build the batch.
    pub inventory: DigestInventory,
    /// Files created or updated, relative to output path.
    pub files_written: Vec<String>,
    /// Existing files skipped because they were not generated by Engram.
    pub files_skipped: Vec<String>,
}

/// Candidate digest file that can later become review-gated source evidence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DigestSourceCandidate {
    /// Source kind inferred from path.
    pub source_kind: DigestSourceKind,
    /// Top-level digest collection directory, such as slack-digest.
    pub collection: String,
    /// Bucket within the collection, such as morning or ai-radar.
    pub bucket: Option<String>,
    /// File format.
    pub format: DigestFileFormat,
    /// Relative path from inventory root.
    pub relative_path: String,
    /// Absolute path.
    pub absolute_path: String,
    /// File name.
    pub file_name: String,
    /// Date or date range inferred from the path, when present.
    pub date_hint: Option<String>,
    /// File size from metadata.
    pub size_bytes: u64,
    /// Last modified timestamp from metadata, when available.
    #[serde(with = "time::serde::rfc3339::option")]
    pub modified_at: Option<OffsetDateTime>,
    /// Sensitivity classification.
    pub sensitivity: DigestSensitivity,
    /// Recommended next action.
    pub proposed_action: DigestProposedAction,
    /// Classification reasons.
    pub reasons: Vec<String>,
}

/// Digest-adjacent file excluded from source candidates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DigestExcludedPath {
    /// Relative path from inventory root.
    pub relative_path: String,
    /// Absolute path.
    pub absolute_path: String,
    /// Exclusion reason.
    pub reason: String,
}

/// Inferred digest source kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestSourceKind {
    /// Slack digest.
    Slack,
    /// Email digest.
    Email,
    /// AI/news digest.
    Ai,
    /// Software engineering digest.
    Swe,
    /// Notes digest.
    Notes,
    /// Unknown digest source.
    Unknown,
}

impl std::fmt::Display for DigestSourceKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Slack => write!(f, "slack"),
            Self::Email => write!(f, "email"),
            Self::Ai => write!(f, "ai"),
            Self::Swe => write!(f, "swe"),
            Self::Notes => write!(f, "notes"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

/// Supported digest file format.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestFileFormat {
    /// Markdown digest.
    Markdown,
    /// HTML digest.
    Html,
}

impl std::fmt::Display for DigestFileFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Markdown => write!(f, "markdown"),
            Self::Html => write!(f, "html"),
        }
    }
}

/// Sensitivity classification for source material.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestSensitivity {
    /// Personal or workplace communication digest.
    SensitiveCommunication,
    /// General notes/news digest.
    PersonalNotes,
}

impl std::fmt::Display for DigestSensitivity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::SensitiveCommunication => write!(f, "sensitive_communication"),
            Self::PersonalNotes => write!(f, "personal_notes"),
        }
    }
}

/// Recommended action for a candidate source file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DigestProposedAction {
    /// Keep as evidence/index source; do not promote directly into memory.
    IndexAsSource,
    /// Generate candidate memories that need review before activation.
    ReviewGatedExtraction,
}

impl std::fmt::Display for DigestProposedAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::IndexAsSource => write!(f, "index_as_source"),
            Self::ReviewGatedExtraction => write!(f, "review_gated_extraction"),
        }
    }
}

fn inventory_digest_sources(options: DigestInventoryOptions) -> IndexResult<DigestInventory> {
    if !options.root_path.exists() {
        return Err(IndexError::FileNotFound(
            options.root_path.display().to_string(),
        ));
    }
    if !options.root_path.is_dir() {
        return Err(IndexError::InvalidState(format!(
            "digest inventory root is not a directory: {}",
            options.root_path.display()
        )));
    }

    let root = fs::canonicalize(&options.root_path)?;
    let mut all_candidates = Vec::new();
    let mut exclusions = Vec::new();
    let mut files_scanned = 0;
    scan_directory(
        &root,
        &root,
        options.include_operational,
        &mut files_scanned,
        &mut all_candidates,
        &mut exclusions,
    )?;

    all_candidates.sort_by(|left, right| {
        left.relative_path
            .cmp(&right.relative_path)
            .then_with(|| left.absolute_path.cmp(&right.absolute_path))
    });
    exclusions.sort_by(|left, right| {
        left.relative_path
            .cmp(&right.relative_path)
            .then_with(|| left.absolute_path.cmp(&right.absolute_path))
    });

    let total_candidates = all_candidates.len();
    let limit = options.limit.unwrap_or(total_candidates);
    let truncated = total_candidates > limit;
    let candidates = all_candidates.into_iter().take(limit).collect::<Vec<_>>();
    let by_source_kind = count_by(
        candidates
            .iter()
            .map(|candidate| candidate.source_kind.to_string()),
    );
    let by_format = count_by(
        candidates
            .iter()
            .map(|candidate| candidate.format.to_string()),
    );
    let by_collection = count_by(
        candidates
            .iter()
            .map(|candidate| candidate.collection.clone()),
    );

    Ok(DigestInventory {
        generated_at: OffsetDateTime::now_utc(),
        root_path: root.display().to_string(),
        files_scanned,
        total_candidates,
        returned_candidates: candidates.len(),
        truncated,
        excluded_count: exclusions.len(),
        by_source_kind,
        by_format,
        by_collection,
        candidates,
        exclusions,
        warnings: vec![
            "Inventory only: no digest contents were read and no Memory OS records were written."
                .to_string(),
            "Digest-derived memories should be generated as review-gated candidates with source evidence."
                .to_string(),
        ],
    })
}

fn export_digest_review_batch(
    output_path: &Path,
    options: DigestInventoryOptions,
) -> IndexResult<DigestReviewExport> {
    let inventory = inventory_digest_sources(options)?;
    fs::create_dir_all(output_path)?;
    let mut export = DigestReviewExport {
        output_path: output_path.display().to_string(),
        inventory,
        files_written: Vec::new(),
        files_skipped: Vec::new(),
    };

    write_digest_review_file(
        output_path,
        Path::new("index.md").to_path_buf(),
        &digest_review_index(&export.inventory),
        &mut export,
    )?;

    let candidates = export.inventory.candidates.clone();
    for (index, candidate) in candidates.iter().enumerate() {
        write_digest_review_file(
            output_path,
            Path::new("candidates").join(format!(
                "{:04}-review-{}.md",
                index + 1,
                slugify(&candidate.relative_path)
            )),
            &digest_review_candidate_page(index + 1, candidate),
            &mut export,
        )?;
    }

    export.files_written.sort();
    export.files_skipped.sort();
    Ok(export)
}

fn digest_review_index(inventory: &DigestInventory) -> String {
    let mut output = digest_review_frontmatter("digest_review_index", Vec::new());
    output.push_str("# Digest Source Review Batch\n\n");
    output.push_str(
        "This generated batch is metadata-only. It does not include digest contents and ",
    );
    output.push_str("does not promote any digest-derived fact into active Memory OS records.\n\n");

    output.push_str("## Summary\n\n");
    output.push_str(&format!("- Root: `{}`\n", inventory.root_path));
    output.push_str(&format!("- Files scanned: {}\n", inventory.files_scanned));
    output.push_str(&format!(
        "- Total candidates: {}\n",
        inventory.total_candidates
    ));
    output.push_str(&format!(
        "- Returned candidates: {}\n",
        inventory.returned_candidates
    ));
    output.push_str(&format!("- Truncated: {}\n", inventory.truncated));
    output.push_str(&format!(
        "- Excluded files: {}\n\n",
        inventory.excluded_count
    ));

    output.push_str("## Candidate Counts\n\n");
    output.push_str("### By Source Kind\n\n");
    append_counts(&mut output, &inventory.by_source_kind);
    output.push_str("\n### By Format\n\n");
    append_counts(&mut output, &inventory.by_format);
    output.push_str("\n### By Collection\n\n");
    append_counts(&mut output, &inventory.by_collection);

    output.push_str("\n## Review Candidates\n\n");
    if inventory.candidates.is_empty() {
        output.push_str("No digest source candidates were found.\n");
    } else {
        for (index, candidate) in inventory.candidates.iter().enumerate() {
            output.push_str(&format!(
                "- [Candidate {:04}](candidates/{:04}-review-{}.md) - `{}` - {} - {}\n",
                index + 1,
                index + 1,
                slugify(&candidate.relative_path),
                candidate.relative_path,
                candidate.source_kind,
                candidate.proposed_action
            ));
        }
    }

    if !inventory.exclusions.is_empty() {
        output.push_str("\n## Exclusions\n\n");
        for exclusion in &inventory.exclusions {
            output.push_str(&format!(
                "- `{}` - {}\n",
                exclusion.relative_path, exclusion.reason
            ));
        }
    }

    output.push_str("\n## Safety\n\n");
    for warning in &inventory.warnings {
        output.push_str(&format!("- {}\n", warning));
    }
    output
}

fn digest_review_candidate_page(index: usize, candidate: &DigestSourceCandidate) -> String {
    let mut fields = vec![
        ("candidate_number".to_string(), index.to_string()),
        (
            "relative_path".to_string(),
            yaml_string(&candidate.relative_path),
        ),
        (
            "source_kind".to_string(),
            yaml_string(&candidate.source_kind.to_string()),
        ),
        ("collection".to_string(), yaml_string(&candidate.collection)),
        (
            "format".to_string(),
            yaml_string(&candidate.format.to_string()),
        ),
        (
            "sensitivity".to_string(),
            yaml_string(&candidate.sensitivity.to_string()),
        ),
        (
            "proposed_action".to_string(),
            yaml_string(&candidate.proposed_action.to_string()),
        ),
    ];
    if let Some(bucket) = &candidate.bucket {
        fields.push(("bucket".to_string(), yaml_string(bucket)));
    }
    if let Some(date_hint) = &candidate.date_hint {
        fields.push(("date_hint".to_string(), yaml_string(date_hint)));
    }

    let mut output = digest_review_frontmatter("digest_review_candidate", fields);
    output.push_str(&format!("# Digest Review: {}\n\n", candidate.relative_path));
    output.push_str("## Source\n\n");
    output.push_str(&format!("- Absolute path: `{}`\n", candidate.absolute_path));
    output.push_str(&format!("- Source kind: `{}`\n", candidate.source_kind));
    output.push_str(&format!("- Collection: `{}`\n", candidate.collection));
    if let Some(bucket) = &candidate.bucket {
        output.push_str(&format!("- Bucket: `{bucket}`\n"));
    }
    if let Some(date_hint) = &candidate.date_hint {
        output.push_str(&format!("- Date hint: `{date_hint}`\n"));
    }
    output.push_str(&format!("- Format: `{}`\n", candidate.format));
    output.push_str(&format!("- Sensitivity: `{}`\n", candidate.sensitivity));
    output.push_str(&format!(
        "- Proposed action: `{}`\n",
        candidate.proposed_action
    ));
    output.push_str(&format!("- Size: {} bytes\n", candidate.size_bytes));
    if let Some(modified_at) = candidate.modified_at {
        output.push_str(&format!("- Modified: {}\n", modified_at));
    }

    output.push_str("\n## Classification Reasons\n\n");
    for reason in &candidate.reasons {
        output.push_str(&format!("- {}\n", reason));
    }

    output.push_str("\n## Review Decision\n\n");
    output.push_str("Set `decision` before a future apply step consumes this file.\n\n");
    output.push_str("```yaml\n");
    output.push_str("decision: pending # accept | reject | quarantine | source_only\n");
    output.push_str("memory_kind: null # preference | rule | decision | limitation | ");
    output.push_str("project_fact | user_fact | task_fact | session_insight\n");
    output.push_str(
        "scope_type: null # global | user | project | task | entity | repository | custom\n",
    );
    output.push_str("scope_name: null\n");
    output.push_str("title: null\n");
    output.push_str("notes: null\n");
    output.push_str("```\n\n");

    output.push_str("## Safety\n\n");
    output.push_str("- This generated page intentionally omits digest contents.\n");
    output.push_str("- Use the source path as evidence if a later reviewed memory is created.\n");
    output.push_str(
        "- Communication digests require explicit review before active memory promotion.\n",
    );
    output
}

fn append_counts(output: &mut String, counts: &BTreeMap<String, usize>) {
    if counts.is_empty() {
        output.push_str("None.\n");
    } else {
        for (key, count) in counts {
            output.push_str(&format!("- {}: {}\n", key, count));
        }
    }
}

fn digest_review_frontmatter(page_type: &str, fields: Vec<(String, String)>) -> String {
    let mut output = String::new();
    output.push_str("---\n");
    output.push_str("generated_by: \"engram-memory-os\"\n");
    output.push_str(&format!("page_type: {}\n", yaml_string(page_type)));
    for (key, value) in fields {
        output.push_str(&format!("{key}: {value}\n"));
    }
    output.push_str("---\n\n");
    output.push_str(DIGEST_REVIEW_MARKER);
    output.push_str("\n\n");
    output
}

fn write_digest_review_file(
    root: &Path,
    relative_path: PathBuf,
    contents: &str,
    export: &mut DigestReviewExport,
) -> IndexResult<()> {
    let path = root.join(&relative_path);
    if path.exists() {
        let existing = fs::read(&path)?;
        if !String::from_utf8_lossy(&existing).contains(DIGEST_REVIEW_MARKER) {
            export.files_skipped.push(path_to_markdown(&relative_path));
            return Ok(());
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, contents)?;
    export.files_written.push(path_to_markdown(&relative_path));
    Ok(())
}

fn scan_directory(
    root: &Path,
    current: &Path,
    include_operational: bool,
    files_scanned: &mut usize,
    candidates: &mut Vec<DigestSourceCandidate>,
    exclusions: &mut Vec<DigestExcludedPath>,
) -> IndexResult<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        let name = entry.file_name();
        let name = name.to_string_lossy();

        if file_type.is_dir() {
            if !include_operational && is_operational_directory(&name) {
                if path_has_digest_component(root, &path) {
                    exclusions.push(exclusion(root, &path, "operational directory"));
                }
                continue;
            }
            scan_directory(
                root,
                &path,
                include_operational,
                files_scanned,
                candidates,
                exclusions,
            )?;
        } else if file_type.is_file() && path_has_digest_component(root, &path) {
            *files_scanned += 1;
            match classify_file(root, &path, include_operational)? {
                FileClassification::Candidate(candidate) => candidates.push(candidate),
                FileClassification::Excluded(excluded) => exclusions.push(excluded),
            }
        }
    }
    Ok(())
}

enum FileClassification {
    Candidate(DigestSourceCandidate),
    Excluded(DigestExcludedPath),
}

fn classify_file(
    root: &Path,
    path: &Path,
    include_operational: bool,
) -> IndexResult<FileClassification> {
    let relative_path = relative_path(root, path);
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string();

    if !include_operational && is_operational_file(&file_name) {
        return Ok(FileClassification::Excluded(exclusion(
            root,
            path,
            "operational artifact",
        )));
    }

    let Some(format) = digest_file_format(path) else {
        return Ok(FileClassification::Excluded(exclusion(
            root,
            path,
            "unsupported digest-adjacent file format",
        )));
    };

    let metadata = fs::metadata(path)?;
    let modified_at = metadata.modified().ok().map(OffsetDateTime::from);
    let collection = digest_collection(root, path).unwrap_or_else(|| "digest".to_string());
    let source_kind = source_kind_from_collection(&collection);
    let bucket = digest_bucket(root, path, &collection);
    let sensitivity = sensitivity_for(source_kind);
    let proposed_action = match sensitivity {
        DigestSensitivity::SensitiveCommunication => DigestProposedAction::ReviewGatedExtraction,
        DigestSensitivity::PersonalNotes => DigestProposedAction::IndexAsSource,
    };
    let mut reasons = vec![
        "Path is under a digest-named collection.".to_string(),
        "Supported source format for future safe parsing.".to_string(),
        "Inventory does not read file contents.".to_string(),
    ];
    if sensitivity == DigestSensitivity::SensitiveCommunication {
        reasons.push(
            "Communication digests must remain review-gated before becoming active memory."
                .to_string(),
        );
    }

    Ok(FileClassification::Candidate(DigestSourceCandidate {
        source_kind,
        collection,
        bucket,
        format,
        relative_path: relative_path.clone(),
        absolute_path: path.display().to_string(),
        file_name,
        date_hint: extract_date_hint(&relative_path),
        size_bytes: metadata.len(),
        modified_at,
        sensitivity,
        proposed_action,
        reasons,
    }))
}

fn digest_file_format(path: &Path) -> Option<DigestFileFormat> {
    match path
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| extension.to_lowercase())
        .as_deref()
    {
        Some("md") | Some("markdown") => Some(DigestFileFormat::Markdown),
        Some("html") | Some("htm") => Some(DigestFileFormat::Html),
        _ => None,
    }
}

fn path_has_digest_component(root: &Path, path: &Path) -> bool {
    if root_digest_collection(root).is_some() {
        return true;
    }

    path.strip_prefix(root)
        .ok()
        .into_iter()
        .flat_map(Path::components)
        .any(|component| {
            component
                .as_os_str()
                .to_string_lossy()
                .to_lowercase()
                .contains("digest")
        })
}

fn digest_collection(root: &Path, path: &Path) -> Option<String> {
    let relative_collection = path
        .strip_prefix(root)
        .ok()?
        .components()
        .find_map(|component| {
            let value = component.as_os_str().to_string_lossy();
            if value.to_lowercase().contains("digest") {
                Some(value.to_string())
            } else {
                None
            }
        });

    relative_collection.or_else(|| root_digest_collection(root))
}

fn root_digest_collection(root: &Path) -> Option<String> {
    let name = root.file_name()?.to_string_lossy();
    if name.to_lowercase().contains("digest") {
        Some(name.to_string())
    } else {
        None
    }
}

fn digest_bucket(root: &Path, path: &Path, collection: &str) -> Option<String> {
    let relative = path.strip_prefix(root).ok()?;
    if root_digest_collection(root).as_deref() == Some(collection) {
        let parent = relative.parent()?;
        if parent.as_os_str().is_empty() {
            return None;
        }
        return Some(
            parent
                .components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/"),
        );
    }

    let mut after_collection = false;
    let mut components = Vec::new();
    for component in relative.components() {
        let value = component.as_os_str().to_string_lossy();
        if !after_collection {
            after_collection = value == collection;
            continue;
        }
        components.push(value.to_string());
    }

    components.pop();
    if components.is_empty() {
        None
    } else {
        Some(components.join("/"))
    }
}

fn source_kind_from_collection(collection: &str) -> DigestSourceKind {
    let lower = collection.to_lowercase();
    if lower.contains("slack") {
        DigestSourceKind::Slack
    } else if lower.contains("mail") || lower.contains("email") {
        DigestSourceKind::Email
    } else if lower.contains("swe") {
        DigestSourceKind::Swe
    } else if lower.contains("ai") {
        DigestSourceKind::Ai
    } else if lower.contains("note") {
        DigestSourceKind::Notes
    } else {
        DigestSourceKind::Unknown
    }
}

fn sensitivity_for(source_kind: DigestSourceKind) -> DigestSensitivity {
    match source_kind {
        DigestSourceKind::Slack | DigestSourceKind::Email => {
            DigestSensitivity::SensitiveCommunication
        }
        DigestSourceKind::Ai
        | DigestSourceKind::Swe
        | DigestSourceKind::Notes
        | DigestSourceKind::Unknown => DigestSensitivity::PersonalNotes,
    }
}

fn is_operational_directory(name: &str) -> bool {
    let lower = name.to_lowercase();
    lower.starts_with('.') || lower == "node_modules" || lower == "target"
}

fn is_operational_file(name: &str) -> bool {
    let lower = name.to_lowercase();
    lower.starts_with('.')
        || lower == "_seen.json"
        || lower == "_queue.json"
        || lower == "skill.md"
        || lower == "settings.local.json"
        || lower.ends_with(".log")
        || lower.ends_with(".yml")
        || lower.ends_with(".yaml")
        || lower.ends_with(".json")
}

fn exclusion(root: &Path, path: &Path, reason: impl Into<String>) -> DigestExcludedPath {
    DigestExcludedPath {
        relative_path: relative_path(root, path),
        absolute_path: path.display().to_string(),
        reason: reason.into(),
    }
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn path_to_markdown(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn slugify(value: &str) -> String {
    let mut slug = String::new();
    let mut previous_dash = false;
    for ch in value.chars().flat_map(char::to_lowercase) {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            slug.push(ch);
            previous_dash = false;
        } else if !previous_dash {
            slug.push('-');
            previous_dash = true;
        }
        if slug.len() >= 80 {
            break;
        }
    }

    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "untitled".to_string()
    } else {
        slug
    }
}

fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

fn extract_date_hint(value: &str) -> Option<String> {
    let bytes = value.as_bytes();
    let mut dates = Vec::new();
    for idx in 0..bytes.len().saturating_sub(9) {
        let candidate = &value[idx..idx + 10];
        if is_iso_date(candidate) {
            dates.push(candidate.to_string());
        }
    }

    match dates.as_slice() {
        [] => None,
        [one] => Some(one.clone()),
        [start, end, ..] => Some(format!("{start}..{end}")),
    }
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[4] == b'-'
        && bytes[7] == b'-'
        && bytes[..4].iter().all(u8::is_ascii_digit)
        && bytes[5..7].iter().all(u8::is_ascii_digit)
        && bytes[8..].iter().all(u8::is_ascii_digit)
}

fn count_by(items: impl Iterator<Item = String>) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for key in items {
        *counts.entry(key).or_insert(0) += 1;
    }
    counts
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn inventory_classifies_digest_sources_without_reading_contents() {
        let dir = tempdir().unwrap();
        fs::create_dir_all(dir.path().join("slack-digest/morning")).unwrap();
        fs::create_dir_all(dir.path().join("mail-digest")).unwrap();
        fs::create_dir_all(dir.path().join("ai-digest/digests")).unwrap();
        fs::write(
            dir.path().join("slack-digest/morning/2026-04-26.md"),
            "private slack content",
        )
        .unwrap();
        fs::write(
            dir.path().join("mail-digest/digest-2026-04-26.html"),
            "<html>private mail content</html>",
        )
        .unwrap();
        fs::write(
            dir.path().join("ai-digest/digests/2026-04-26.md"),
            "AI digest",
        )
        .unwrap();
        fs::write(dir.path().join("ai-digest/_seen.json"), "{}").unwrap();
        fs::write(dir.path().join("ai-digest/SKILL.md"), "# skill").unwrap();

        let inventory = DigestService::new()
            .inventory(DigestInventoryOptions::new(dir.path()))
            .unwrap();

        assert_eq!(inventory.files_scanned, 5);
        assert_eq!(inventory.total_candidates, 3);
        assert_eq!(inventory.excluded_count, 2);
        assert_eq!(inventory.by_source_kind["slack"], 1);
        assert_eq!(inventory.by_source_kind["email"], 1);
        assert_eq!(inventory.by_source_kind["ai"], 1);
        assert!(inventory
            .candidates
            .iter()
            .any(|candidate| candidate.bucket.as_deref() == Some("morning")));
        assert!(inventory
            .exclusions
            .iter()
            .any(|excluded| excluded.relative_path.ends_with("_seen.json")));
        assert!(inventory
            .warnings
            .iter()
            .any(|warning| warning.contains("no digest contents were read")));
    }

    #[test]
    fn inventory_limit_truncates_candidates_after_counting() {
        let dir = tempdir().unwrap();
        fs::create_dir_all(dir.path().join("notes-digest")).unwrap();
        fs::write(dir.path().join("notes-digest/digest-2026-04-25.md"), "one").unwrap();
        fs::write(dir.path().join("notes-digest/digest-2026-04-26.md"), "two").unwrap();

        let mut options = DigestInventoryOptions::new(dir.path());
        options.limit = Some(1);
        let inventory = DigestService::new().inventory(options).unwrap();

        assert_eq!(inventory.total_candidates, 2);
        assert_eq!(inventory.returned_candidates, 1);
        assert!(inventory.truncated);
    }

    #[test]
    fn inventory_accepts_digest_directory_as_root() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("slack-digest");
        fs::create_dir_all(root.join("evening")).unwrap();
        fs::write(root.join("evening/2026-04-26.md"), "digest").unwrap();

        let inventory = DigestService::new()
            .inventory(DigestInventoryOptions::new(&root))
            .unwrap();

        assert_eq!(inventory.total_candidates, 1);
        assert_eq!(inventory.candidates[0].collection, "slack-digest");
        assert_eq!(inventory.candidates[0].bucket.as_deref(), Some("evening"));
    }

    #[test]
    fn inventory_prefers_child_collection_over_digest_named_root() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("digest-smoke-root");
        fs::create_dir_all(root.join("slack-digest/morning")).unwrap();
        fs::write(root.join("slack-digest/morning/2026-04-26.md"), "digest").unwrap();

        let inventory = DigestService::new()
            .inventory(DigestInventoryOptions::new(&root))
            .unwrap();

        assert_eq!(inventory.total_candidates, 1);
        assert_eq!(inventory.candidates[0].collection, "slack-digest");
        assert_eq!(inventory.candidates[0].source_kind, DigestSourceKind::Slack);
        assert_eq!(inventory.candidates[0].bucket.as_deref(), Some("morning"));
    }

    #[test]
    fn review_export_writes_index_and_candidate_pages_without_contents() {
        let dir = tempdir().unwrap();
        let output = tempdir().unwrap();
        fs::create_dir_all(dir.path().join("slack-digest/morning")).unwrap();
        fs::create_dir_all(dir.path().join("mail-digest")).unwrap();
        fs::write(
            dir.path().join("slack-digest/morning/2026-04-26.md"),
            "private slack content",
        )
        .unwrap();
        fs::write(
            dir.path().join("mail-digest/digest-2026-04-26.html"),
            "<html>private mail content</html>",
        )
        .unwrap();
        fs::write(dir.path().join("mail-digest/_queue.json"), "{}").unwrap();

        let export = DigestService::new()
            .export_review_batch(output.path(), DigestInventoryOptions::new(dir.path()))
            .unwrap();

        assert_eq!(export.inventory.total_candidates, 2);
        assert!(export.files_written.iter().any(|path| path == "index.md"));
        assert!(export
            .files_written
            .iter()
            .any(|path| path.starts_with("candidates/")));

        let index = fs::read_to_string(output.path().join("index.md")).unwrap();
        assert!(index.contains("# Digest Source Review Batch"));
        assert!(index.contains(DIGEST_REVIEW_MARKER));
        assert!(!index.contains("private slack content"));
        assert!(!index.contains("private mail content"));

        let candidate_path = export
            .files_written
            .iter()
            .find(|path| path.starts_with("candidates/"))
            .expect("candidate review page should be written");
        let candidate = fs::read_to_string(output.path().join(candidate_path)).unwrap();
        assert!(candidate.contains("decision: pending"));
        assert!(candidate.contains("This generated page intentionally omits digest contents."));
        assert!(!candidate.contains("private slack content"));
        assert!(!candidate.contains("private mail content"));
    }

    #[test]
    fn review_export_skips_user_owned_files() {
        let dir = tempdir().unwrap();
        let output = tempdir().unwrap();
        fs::create_dir_all(dir.path().join("notes-digest")).unwrap();
        fs::write(
            dir.path().join("notes-digest/digest-2026-04-26.md"),
            "private notes content",
        )
        .unwrap();
        fs::write(
            output.path().join("index.md"),
            "# Human review notes\n\nDo not replace this file.\n",
        )
        .unwrap();

        let export = DigestService::new()
            .export_review_batch(output.path(), DigestInventoryOptions::new(dir.path()))
            .unwrap();

        assert!(export.files_skipped.iter().any(|path| path == "index.md"));
        let index = fs::read_to_string(output.path().join("index.md")).unwrap();
        assert!(index.contains("Do not replace this file."));
        assert!(!index.contains(DIGEST_REVIEW_MARKER));
    }

    #[test]
    fn review_export_rejects_missing_root_without_creating_output() {
        let dir = tempdir().unwrap();
        let output = dir.path().join("review-output");

        let err = DigestService::new()
            .export_review_batch(
                &output,
                DigestInventoryOptions::new(dir.path().join("missing")),
            )
            .unwrap_err();

        assert!(err.to_string().contains("file not found"));
        assert!(!output.exists());
    }

    #[test]
    fn inventory_rejects_missing_root() {
        let dir = tempdir().unwrap();
        let err = DigestService::new()
            .inventory(DigestInventoryOptions::new(dir.path().join("missing")))
            .unwrap_err();

        assert!(err.to_string().contains("file not found"));
    }

    #[test]
    fn date_hint_extracts_single_dates_and_ranges() {
        assert_eq!(
            extract_date_hint("slack-digest/morning/2026-04-26.md"),
            Some("2026-04-26".to_string())
        );
        assert_eq!(
            extract_date_hint("catchup/2026-02-26-to-2026-03-29.md"),
            Some("2026-02-26..2026-03-29".to_string())
        );
        assert_eq!(extract_date_hint("handoff.md"), None);
    }
}
