//! Markdown vault export for Memory OS.
//!
//! This module projects typed memory records into deterministic Markdown files
//! that can be opened in Obsidian or read directly by an agent. It deliberately
//! treats the vault as a generated projection: existing files without the Engram
//! generated marker are skipped instead of overwritten.

use crate::error::IndexResult;
use engram_core::memory::{
    ClaimOrigin, EvidenceKind, KnowledgeCommit, MemoryChangeType, MemoryItem, MemoryScope,
};
use engram_core::repository::{
    GitRepository, LocalCheckout, MonorepoComponent, ProjectRepositoryLink,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use time::OffsetDateTime;

const GENERATED_BY: &str = "engram-memory-os";
const GENERATED_MARKER: &str = "<!-- engram:generated:file memory-vault-v1 -->";

/// Summary of a vault export operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryVaultExport {
    /// Vault root path.
    pub root: String,
    /// Files created or updated, relative to root.
    pub files_written: Vec<String>,
    /// Existing files skipped because they were not generated by Engram.
    pub files_skipped: Vec<String>,
    /// Exported memory item count.
    pub memory_item_count: usize,
    /// Exported knowledge commit count.
    pub knowledge_commit_count: usize,
    /// Exported repository page count.
    pub repository_count: usize,
    /// Exported project page count.
    pub project_count: usize,
}

impl MemoryVaultExport {
    /// Number of files written by this export.
    #[must_use]
    pub fn file_count(&self) -> usize {
        self.files_written.len()
    }
}

/// Repository topology data included in the vault export.
#[derive(Debug, Clone)]
pub struct RepositoryVaultSnapshot {
    /// Canonical repository.
    pub repository: GitRepository,
    /// Known local checkouts for this repository.
    pub checkouts: Vec<LocalCheckout>,
    /// Registered monorepo components.
    pub components: Vec<MonorepoComponent>,
    /// Project links for the repository.
    pub project_links: Vec<ProjectRepositoryLink>,
}

/// Write a deterministic Markdown vault projection.
pub(crate) fn write_memory_vault(
    root: &Path,
    items: &[MemoryItem],
    commits: &[KnowledgeCommit],
    repositories: &[RepositoryVaultSnapshot],
) -> IndexResult<MemoryVaultExport> {
    fs::create_dir_all(root)?;

    let mut export = MemoryVaultExport {
        root: root.display().to_string(),
        files_written: Vec::new(),
        files_skipped: Vec::new(),
        memory_item_count: items.len(),
        knowledge_commit_count: commits.len(),
        repository_count: repositories.len(),
        project_count: 0,
    };

    let mut sorted_items = items.to_vec();
    sorted_items.sort_by(|left, right| {
        left.updated_at
            .cmp(&right.updated_at)
            .then_with(|| left.title.cmp(&right.title))
            .then_with(|| left.id.to_string().cmp(&right.id.to_string()))
    });

    let mut sorted_commits = commits.to_vec();
    sorted_commits.sort_by(|left, right| {
        left.created_at
            .cmp(&right.created_at)
            .then_with(|| left.id.to_string().cmp(&right.id.to_string()))
    });

    let mut sorted_repositories = repositories.to_vec();
    sorted_repositories.sort_by(|left, right| {
        left.repository
            .name
            .cmp(&right.repository.name)
            .then_with(|| {
                left.repository
                    .id
                    .to_string()
                    .cmp(&right.repository.id.to_string())
            })
    });

    let project_names = project_names(&sorted_items, &sorted_repositories);
    export.project_count = project_names.len();

    write_generated_file(
        root,
        Path::new("99_System").join("Vault-Index.md"),
        &vault_index(
            &sorted_items,
            &sorted_commits,
            &sorted_repositories,
            &project_names,
        ),
        &mut export,
    )?;
    write_generated_file(
        root,
        Path::new("memory").join("index.md"),
        &memory_index(&sorted_items, &sorted_commits),
        &mut export,
    )?;

    for item in &sorted_items {
        write_generated_file(
            root,
            item_relative_path(item),
            &memory_item_page(item),
            &mut export,
        )?;
    }

    for commit in &sorted_commits {
        write_generated_file(
            root,
            commit_relative_path(commit),
            &knowledge_commit_page(commit),
            &mut export,
        )?;
    }

    write_generated_file(
        root,
        Path::new("repositories").join("index.md"),
        &repositories_index(&sorted_repositories),
        &mut export,
    )?;
    for repository in &sorted_repositories {
        write_generated_file(
            root,
            repository_relative_path(&repository.repository),
            &repository_page(repository),
            &mut export,
        )?;
    }

    for project_name in project_names {
        write_generated_file(
            root,
            project_relative_path(&project_name),
            &project_page(&project_name, &sorted_items, &sorted_repositories),
            &mut export,
        )?;
    }

    export.files_written.sort();
    export.files_skipped.sort();
    Ok(export)
}

fn vault_index(
    items: &[MemoryItem],
    commits: &[KnowledgeCommit],
    repositories: &[RepositoryVaultSnapshot],
    project_names: &BTreeSet<String>,
) -> String {
    let mut output = frontmatter("vault_index", Vec::new());
    output.push_str("# Engram Memory Vault\n\n");
    output.push_str("## Summary\n\n");
    output.push_str(&format!("- Memory items: {}\n", items.len()));
    output.push_str(&format!("- Knowledge commits: {}\n", commits.len()));
    output.push_str(&format!("- Repositories: {}\n", repositories.len()));
    output.push_str(&format!("- Projects: {}\n\n", project_names.len()));

    output.push_str("## Entry Points\n\n");
    output.push_str("- [Memory](../memory/index.md)\n");
    output.push_str("- [Repositories](../repositories/index.md)\n");
    if !project_names.is_empty() {
        output.push_str("- Projects\n");
        for project_name in project_names {
            output.push_str(&format!(
                "  - [{}](../{})\n",
                escape_link_text(project_name),
                path_to_markdown(&project_relative_path(project_name))
            ));
        }
    }
    output
}

fn memory_index(items: &[MemoryItem], commits: &[KnowledgeCommit]) -> String {
    let mut output = frontmatter("memory_index", Vec::new());
    output.push_str("# Memory\n\n");
    output.push_str("## Status Counts\n\n");
    for (status, count) in status_counts(items) {
        output.push_str(&format!("- {}: {}\n", status, count));
    }

    output.push_str("\n## Items\n\n");
    for item in items {
        output.push_str(&format!(
            "- [{}](items/{}) - {} - {}\n",
            escape_link_text(&item.title),
            file_name(&item_relative_path(item)),
            item.kind,
            item.status
        ));
    }

    output.push_str("\n## Knowledge Commits\n\n");
    for commit in commits {
        output.push_str(&format!(
            "- [{}](commits/{}) - {} change(s)\n",
            escape_link_text(&commit.message),
            file_name(&commit_relative_path(commit)),
            commit.change_count()
        ));
    }
    output
}

fn memory_item_page(item: &MemoryItem) -> String {
    let mut fields = vec![
        ("engram_id".to_string(), yaml_string(&item.id.to_string())),
        ("kind".to_string(), yaml_string(&item.kind.to_string())),
        ("status".to_string(), yaml_string(&item.status.to_string())),
        (
            "scope_type".to_string(),
            yaml_string(memory_scope_type(&item.scope)),
        ),
        (
            "scope".to_string(),
            yaml_string(&memory_scope_label(&item.scope)),
        ),
        (
            "origin".to_string(),
            yaml_string(&claim_origin_label(&item.origin)),
        ),
        (
            "confidence".to_string(),
            format!("{:.3}", item.confidence.value()),
        ),
        (
            "writer_harness".to_string(),
            yaml_string(&item.writer.harness.to_string()),
        ),
        (
            "writer_model_provider".to_string(),
            yaml_string(&item.writer.model.provider),
        ),
        (
            "writer_model".to_string(),
            yaml_string(&item.writer.model.model),
        ),
        (
            "created_at".to_string(),
            yaml_string(&format_time(item.created_at)),
        ),
        (
            "updated_at".to_string(),
            yaml_string(&format_time(item.updated_at)),
        ),
    ];
    push_optional_field(
        &mut fields,
        "writer_surface",
        item.writer.surface.as_deref(),
    );
    push_optional_field(
        &mut fields,
        "writer_model_version",
        item.writer.model.version.as_deref(),
    );
    if let Some(review_after) = item.review_after {
        fields.push((
            "review_after".to_string(),
            yaml_string(&format_time(review_after)),
        ));
    }

    let mut output = frontmatter("memory_item", fields);
    output.push_str(&format!("# {}\n\n", item.title));
    output.push_str(&item.content);
    output.push_str("\n\n## Metadata\n\n");
    output.push_str(&format!("- Kind: {}\n", item.kind));
    output.push_str(&format!("- Status: {}\n", item.status));
    output.push_str(&format!("- Scope: {}\n", memory_scope_label(&item.scope)));
    output.push_str(&format!("- Origin: {}\n", claim_origin_label(&item.origin)));
    output.push_str(&format!("- Confidence: {:.3}\n", item.confidence.value()));
    output.push_str(&format!(
        "- Writer: {} / {} / {}\n",
        item.writer.harness, item.writer.model.provider, item.writer.model.model
    ));
    if !item.tags.is_empty() {
        output.push_str(&format!("- Tags: {}\n", item.tags.join(", ")));
    }
    if !item.supersedes.is_empty() {
        output.push_str("- Supersedes:\n");
        for id in &item.supersedes {
            output.push_str(&format!("  - {}\n", id));
        }
    }

    output.push_str("\n## Evidence\n\n");
    if item.evidence.is_empty() {
        output.push_str("No evidence recorded.\n");
    } else {
        for evidence in &item.evidence {
            output.push_str(&format!(
                "- {}: {}",
                evidence_kind_label(&evidence.kind),
                evidence.target
            ));
            if let Some(summary) = &evidence.summary {
                output.push_str(&format!(" - {}", summary));
            }
            output.push('\n');
            if let Some(excerpt) = &evidence.excerpt {
                output.push_str(&format!("  - Excerpt: {}\n", excerpt));
            }
        }
    }

    output
}

fn knowledge_commit_page(commit: &KnowledgeCommit) -> String {
    let fields = vec![
        ("engram_id".to_string(), yaml_string(&commit.id.to_string())),
        ("message".to_string(), yaml_string(&commit.message)),
        (
            "writer_harness".to_string(),
            yaml_string(&commit.writer.harness.to_string()),
        ),
        (
            "writer_model".to_string(),
            yaml_string(&commit.writer.model.model),
        ),
        (
            "created_at".to_string(),
            yaml_string(&format_time(commit.created_at)),
        ),
    ];

    let mut output = frontmatter("knowledge_commit", fields);
    output.push_str(&format!("# {}\n\n", commit.message));
    output.push_str("## Commit\n\n");
    output.push_str(&format!("- ID: {}\n", commit.id));
    if let Some(parent_id) = commit.parent_id {
        output.push_str(&format!("- Parent: {}\n", parent_id));
    }
    if let Some(session_id) = commit.session_id {
        output.push_str(&format!("- Session: {}\n", session_id));
    }
    output.push_str(&format!(
        "- Writer: {} / {} / {}\n",
        commit.writer.harness, commit.writer.model.provider, commit.writer.model.model
    ));

    output.push_str("\n## Changes\n\n");
    if commit.changes.is_empty() {
        output.push_str("No changes recorded.\n");
    } else {
        for change in &commit.changes {
            output.push_str(&format!(
                "- {}: {} - {}\n",
                memory_change_type_label(change.change_type),
                change.title,
                change.summary
            ));
            if let Some(item_id) = change.item_id {
                output.push_str(&format!("  - Item: {}\n", item_id));
            }
            if change.before_hash.is_some() || change.after_hash.is_some() {
                output.push_str(&format!(
                    "  - Hash: {} -> {}\n",
                    change.before_hash.as_deref().unwrap_or("unknown"),
                    change.after_hash.as_deref().unwrap_or("unknown")
                ));
            }
        }
    }
    output
}

fn repositories_index(repositories: &[RepositoryVaultSnapshot]) -> String {
    let mut output = frontmatter("repositories_index", Vec::new());
    output.push_str("# Repositories\n\n");
    if repositories.is_empty() {
        output.push_str("No repositories registered.\n");
    } else {
        for snapshot in repositories {
            output.push_str(&format!(
                "- [{}]({})",
                escape_link_text(&snapshot.repository.name),
                path_to_markdown(&repository_relative_path(&snapshot.repository))
            ));
            if let Some(remote_url) = &snapshot.repository.remote_url {
                output.push_str(&format!(" - {}", remote_url));
            }
            output.push('\n');
        }
    }
    output
}

fn repository_page(snapshot: &RepositoryVaultSnapshot) -> String {
    let repository = &snapshot.repository;
    let fields = vec![
        (
            "engram_id".to_string(),
            yaml_string(&repository.id.to_string()),
        ),
        ("repository_name".to_string(), yaml_string(&repository.name)),
        (
            "provider".to_string(),
            yaml_string(&repository.provider.to_string()),
        ),
    ];
    let mut output = frontmatter("repository", fields);
    output.push_str(&format!("# Repository: {}\n\n", repository.name));

    output.push_str("## Source\n\n");
    output.push_str(&format!("- ID: {}\n", repository.id));
    output.push_str(&format!("- Provider: {}\n", repository.provider));
    if let Some(remote_url) = &repository.remote_url {
        output.push_str(&format!("- Remote: {}\n", remote_url));
    }
    if let Some(default_branch) = &repository.default_branch {
        output.push_str(&format!("- Default branch: {}\n", default_branch));
    }
    if let Some(description) = &repository.description {
        output.push_str(&format!("- Description: {}\n", description));
    }

    output.push_str("\n## Local Checkouts\n\n");
    if snapshot.checkouts.is_empty() {
        output.push_str("No local checkouts registered.\n");
    } else {
        for checkout in &snapshot.checkouts {
            output.push_str(&format!("- {}\n", checkout.local_path));
            if let Some(branch) = &checkout.current_branch {
                output.push_str(&format!("  - Branch: {}\n", branch));
            }
            if let Some(head_sha) = &checkout.head_sha {
                output.push_str(&format!("  - HEAD: {}\n", head_sha));
            }
            if let Some(is_dirty) = checkout.is_dirty {
                output.push_str(&format!("  - Dirty: {}\n", is_dirty));
            }
        }
    }

    output.push_str("\n## Project Links\n\n");
    if snapshot.project_links.is_empty() {
        output.push_str("No project links registered.\n");
    } else {
        for link in &snapshot.project_links {
            output.push_str(&format!("- {} ({})", link.project_name, link.role));
            if let Some(component_path) = &link.component_path {
                output.push_str(&format!(" - component: {}", component_path));
            }
            output.push('\n');
        }
    }

    output.push_str("\n## Components\n\n");
    if snapshot.components.is_empty() {
        output.push_str("No monorepo components registered.\n");
    } else {
        for component in &snapshot.components {
            output.push_str(&format!("- {} ({})", component.name, component.path));
            if let Some(kind) = &component.kind {
                output.push_str(&format!(" - {}", kind));
            }
            if let Some(description) = &component.description {
                output.push_str(&format!(" - {}", description));
            }
            output.push('\n');
        }
    }

    output
}

fn project_page(
    project_name: &str,
    items: &[MemoryItem],
    repositories: &[RepositoryVaultSnapshot],
) -> String {
    let fields = vec![("project_name".to_string(), yaml_string(project_name))];
    let mut output = frontmatter("project", fields);
    output.push_str(&format!("# Project: {}\n\n", project_name));

    output.push_str("## Memory Items\n\n");
    let project_items: Vec<_> = items
        .iter()
        .filter(|item| memory_scope_project_name(&item.scope) == Some(project_name))
        .collect();
    if project_items.is_empty() {
        output.push_str("No project-scoped memory items exported.\n");
    } else {
        for item in project_items {
            output.push_str(&format!(
                "- [{}](../../{}) - {} - {}\n",
                escape_link_text(&item.title),
                path_to_markdown(&item_relative_path(item)),
                item.kind,
                item.status
            ));
        }
    }

    output.push_str("\n## Repositories\n\n");
    let mut wrote_repository = false;
    for snapshot in repositories {
        let links: Vec<_> = snapshot
            .project_links
            .iter()
            .filter(|link| link.project_name.eq_ignore_ascii_case(project_name))
            .collect();
        if links.is_empty() {
            continue;
        }
        wrote_repository = true;
        output.push_str(&format!(
            "- [{}](../../{})\n",
            escape_link_text(&snapshot.repository.name),
            path_to_markdown(&repository_relative_path(&snapshot.repository))
        ));
        for link in links {
            output.push_str(&format!("  - Role: {}", link.role));
            if let Some(component_path) = &link.component_path {
                output.push_str(&format!("; component: {}", component_path));
            }
            output.push('\n');
        }
    }
    if !wrote_repository {
        output.push_str("No repositories linked to this project.\n");
    }

    output
}

fn status_counts(items: &[MemoryItem]) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for item in items {
        *counts.entry(item.status.to_string()).or_insert(0) += 1;
    }
    counts
}

fn project_names(
    items: &[MemoryItem],
    repositories: &[RepositoryVaultSnapshot],
) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in items {
        if let Some(project_name) = memory_scope_project_name(&item.scope) {
            names.insert(project_name.to_string());
        }
    }
    for snapshot in repositories {
        for link in &snapshot.project_links {
            names.insert(link.project_name.clone());
        }
    }
    names
}

fn memory_scope_project_name(scope: &MemoryScope) -> Option<&str> {
    match scope {
        MemoryScope::Project { project_name, .. } => Some(project_name.as_str()),
        MemoryScope::Task { project_name, .. } => project_name.as_deref(),
        _ => None,
    }
}

fn memory_scope_type(scope: &MemoryScope) -> &'static str {
    match scope {
        MemoryScope::Global => "global",
        MemoryScope::User => "user",
        MemoryScope::Project { .. } => "project",
        MemoryScope::Task { .. } => "task",
        MemoryScope::Entity { .. } => "entity",
        MemoryScope::Repository { .. } => "repository",
        MemoryScope::Session { .. } => "session",
        MemoryScope::Custom { .. } => "custom",
    }
}

fn memory_scope_label(scope: &MemoryScope) -> String {
    match scope {
        MemoryScope::Global => "global".to_string(),
        MemoryScope::User => "user".to_string(),
        MemoryScope::Project { project_name, .. } => format!("project:{project_name}"),
        MemoryScope::Task {
            project_name,
            task_name,
            ..
        } => project_name
            .as_ref()
            .map(|project| format!("task:{project}/{task_name}"))
            .unwrap_or_else(|| format!("task:{task_name}")),
        MemoryScope::Entity { entity_name, .. } => format!("entity:{entity_name}"),
        MemoryScope::Repository {
            repository_id,
            remote_url,
            local_path,
        } => repository_id
            .map(|id| format!("repository:{id}"))
            .or_else(|| remote_url.as_ref().map(|url| format!("repository:{url}")))
            .or_else(|| local_path.as_ref().map(|path| format!("repository:{path}")))
            .unwrap_or_else(|| "repository".to_string()),
        MemoryScope::Session { session_id } => format!("session:{session_id}"),
        MemoryScope::Custom { name } => format!("custom:{name}"),
    }
}

fn claim_origin_label(origin: &ClaimOrigin) -> String {
    match origin {
        ClaimOrigin::UserStated => "user_stated".to_string(),
        ClaimOrigin::UserCorrected => "user_corrected".to_string(),
        ClaimOrigin::AgentObserved => "agent_observed".to_string(),
        ClaimOrigin::AgentInferred => "agent_inferred".to_string(),
        ClaimOrigin::ToolResult => "tool_result".to_string(),
        ClaimOrigin::Imported => "imported".to_string(),
        ClaimOrigin::Migrated => "migrated".to_string(),
        ClaimOrigin::GeneratedSummary => "generated_summary".to_string(),
        ClaimOrigin::Custom(value) => value.clone(),
    }
}

fn evidence_kind_label(kind: &EvidenceKind) -> String {
    match kind {
        EvidenceKind::SessionEvent => "session_event".to_string(),
        EvidenceKind::ToolCall => "tool_call".to_string(),
        EvidenceKind::File => "file".to_string(),
        EvidenceKind::GitCommit => "git_commit".to_string(),
        EvidenceKind::Url => "url".to_string(),
        EvidenceKind::Document => "document".to_string(),
        EvidenceKind::Observation => "observation".to_string(),
        EvidenceKind::ManualReview => "manual_review".to_string(),
        EvidenceKind::Custom(value) => value.clone(),
    }
}

fn memory_change_type_label(change_type: MemoryChangeType) -> &'static str {
    match change_type {
        MemoryChangeType::Added => "added",
        MemoryChangeType::Updated => "updated",
        MemoryChangeType::Superseded => "superseded",
        MemoryChangeType::Archived => "archived",
        MemoryChangeType::Rejected => "rejected",
        MemoryChangeType::Linked => "linked",
        MemoryChangeType::Unlinked => "unlinked",
    }
}

fn frontmatter(page_type: &str, fields: Vec<(String, String)>) -> String {
    let mut output = String::new();
    output.push_str("---\n");
    output.push_str(&format!("generated_by: {}\n", yaml_string(GENERATED_BY)));
    output.push_str(&format!("page_type: {}\n", yaml_string(page_type)));
    for (key, value) in fields {
        output.push_str(&format!("{key}: {value}\n"));
    }
    output.push_str("---\n\n");
    output.push_str(GENERATED_MARKER);
    output.push_str("\n\n");
    output
}

fn push_optional_field(fields: &mut Vec<(String, String)>, key: &str, value: Option<&str>) {
    if let Some(value) = value {
        fields.push((key.to_string(), yaml_string(value)));
    }
}

fn write_generated_file(
    root: &Path,
    relative_path: PathBuf,
    contents: &str,
    export: &mut MemoryVaultExport,
) -> IndexResult<()> {
    let path = root.join(&relative_path);
    if path.exists() {
        let existing = fs::read(&path)?;
        if !String::from_utf8_lossy(&existing).contains(GENERATED_MARKER) {
            export.files_skipped.push(path_to_markdown(&relative_path));
            return Ok(());
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, contents)?;
    export.files_written.push(path_to_markdown(&relative_path));
    Ok(())
}

fn item_relative_path(item: &MemoryItem) -> PathBuf {
    Path::new("memory")
        .join("items")
        .join(format!("{}-{}.md", item.id, slugify(&item.title)))
}

fn commit_relative_path(commit: &KnowledgeCommit) -> PathBuf {
    Path::new("memory").join("commits").join(format!(
        "{}-{}.md",
        commit.id,
        slugify(&commit.message)
    ))
}

fn repository_relative_path(repository: &GitRepository) -> PathBuf {
    Path::new("repositories").join(format!(
        "{}-{}.md",
        slugify(&repository.name),
        repository.id
    ))
}

fn project_relative_path(project_name: &str) -> PathBuf {
    Path::new("projects")
        .join(slugify(project_name))
        .join("index.md")
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string()
}

fn path_to_markdown(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn slugify(value: &str) -> String {
    let mut slug = String::new();
    let mut previous_dash = false;
    for ch in value.chars().flat_map(char::to_lowercase) {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            slug.push(ch);
            previous_dash = false;
        } else if !previous_dash {
            slug.push('-');
            previous_dash = true;
        }
        if slug.len() >= 80 {
            break;
        }
    }

    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "untitled".to_string()
    } else {
        slug
    }
}

fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

fn escape_link_text(value: &str) -> String {
    value.replace('\\', "\\\\").replace(']', "\\]")
}

fn format_time(value: OffsetDateTime) -> String {
    value
        .format(&time::format_description::well_known::Rfc3339)
        .expect("RFC3339 timestamp formatting should succeed")
}

#[cfg(test)]
mod tests {
    use super::*;
    use engram_core::memory::{
        ClaimOrigin, EvidenceRef, Harness, KnowledgeCommit, MemoryChange, MemoryChangeType,
        MemoryKind, ModelIdentity, WriterProvenance,
    };
    use engram_core::repository::{ProjectRepositoryRole, RepositoryProvider};
    use tempfile::tempdir;

    fn writer() -> WriterProvenance {
        WriterProvenance::agent(Harness::Codex, ModelIdentity::new("openai", "gpt-5.5"))
            .with_surface("desktop")
    }

    fn memory_item(title: &str) -> MemoryItem {
        MemoryItem::new(
            MemoryKind::Decision,
            title,
            "Use a deterministic Markdown projection for Memory OS.",
            MemoryScope::project("engram"),
            ClaimOrigin::UserStated,
            writer(),
        )
        .with_evidence(EvidenceRef::new(EvidenceKind::ManualReview, "vault-test"))
        .with_tag("memory-os")
    }

    #[test]
    fn write_memory_vault_creates_generated_pages() {
        let dir = tempdir().unwrap();
        let item = memory_item("Write vault pages");
        let commit = KnowledgeCommit::new(writer(), "Capture vault export").with_change(
            MemoryChange::new(
                MemoryChangeType::Added,
                "Write vault pages",
                "Added vault page export.",
            )
            .with_item(item.id),
        );
        let repository = GitRepository::new("engram")
            .with_remote_url("git@github.com:ymeiri/engram.git")
            .with_provider(RepositoryProvider::GitHub);
        let link =
            ProjectRepositoryLink::new("engram", repository.id, ProjectRepositoryRole::Primary);
        let snapshot = RepositoryVaultSnapshot {
            repository,
            checkouts: Vec::new(),
            components: Vec::new(),
            project_links: vec![link],
        };

        let export = write_memory_vault(
            dir.path(),
            std::slice::from_ref(&item),
            &[commit],
            &[snapshot],
        )
        .unwrap();

        assert_eq!(export.memory_item_count, 1);
        assert_eq!(export.knowledge_commit_count, 1);
        assert_eq!(export.repository_count, 1);
        assert_eq!(export.project_count, 1);
        assert!(export.files_skipped.is_empty());
        assert!(export
            .files_written
            .iter()
            .any(|path| path.starts_with("memory/items/")));
        assert!(dir.path().join("memory/index.md").exists());

        let item_path = dir.path().join(item_relative_path(&item));
        let item_page = fs::read_to_string(item_path).unwrap();
        assert!(item_page.contains(GENERATED_MARKER));
        assert!(item_page.contains("generated_by: \"engram-memory-os\""));
        assert!(item_page.contains("# Write vault pages"));
        assert!(item_page.contains("manual_review: vault-test"));
    }

    #[test]
    fn write_memory_vault_skips_user_owned_files() {
        let dir = tempdir().unwrap();
        let index_path = dir.path().join("memory/index.md");
        fs::create_dir_all(index_path.parent().unwrap()).unwrap();
        fs::write(&index_path, "# User owned\n").unwrap();

        let export = write_memory_vault(dir.path(), &[], &[], &[]).unwrap();

        assert!(export
            .files_skipped
            .contains(&"memory/index.md".to_string()));
        let index = fs::read_to_string(index_path).unwrap();
        assert_eq!(index, "# User owned\n");
    }
}
