//! Markdown vault export for Memory OS.
//!
//! This module projects typed memory records into deterministic Markdown files
//! that can be opened in Obsidian or read directly by an agent. It deliberately
//! treats the vault as a generated projection: existing files without the Engram
//! generated marker are skipped instead of overwritten.

use crate::error::{IndexError, IndexResult};
use engram_core::memory::{
    ClaimOrigin, EvidenceKind, KnowledgeCommit, MemoryChangeType, MemoryItem, MemoryScope,
};
use engram_core::repository::{
    GitRepository, LocalCheckout, MonorepoComponent, ProjectRepositoryLink,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, Path, PathBuf};
use time::OffsetDateTime;

const GENERATED_BY: &str = "engram-memory-os";
const GENERATED_MARKER: &str = "<!-- engram:generated:file memory-vault-v1 -->";
const VAULT_DIRECTORIES: &[&str] = &[
    "99_System",
    "memory",
    "memory/items",
    "memory/commits",
    "entities",
    "projects",
    "repositories",
];

/// Summary of a vault export operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryVaultExport {
    /// Vault root path.
    pub root: String,
    /// Files created or updated, relative to root.
    pub files_written: Vec<String>,
    /// Existing files skipped because they were not generated by Engram.
    pub files_skipped: Vec<String>,
    /// Exported memory item count.
    pub memory_item_count: usize,
    /// Exported knowledge commit count.
    pub knowledge_commit_count: usize,
    /// Exported repository page count.
    pub repository_count: usize,
    /// Exported entity page count.
    pub entity_count: usize,
    /// Exported project page count.
    pub project_count: usize,
}

impl MemoryVaultExport {
    /// Number of files written by this export.
    #[must_use]
    pub fn file_count(&self) -> usize {
        self.files_written.len()
    }
}

/// Summary of a vault initialization operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryVaultInit {
    /// Vault root path.
    pub root: String,
    /// Directories created, relative to root.
    pub directories_created: Vec<String>,
    /// Directories already present, relative to root.
    pub directories_existing: Vec<String>,
}

/// Read-only status for a generated Memory OS vault.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryVaultStatus {
    /// Vault root path.
    pub root: String,
    /// Whether the root path exists.
    pub exists: bool,
    /// Whether the expected directory skeleton exists.
    pub initialized: bool,
    /// Missing expected directories, relative to root.
    pub missing_directories: Vec<String>,
    /// Number of files under the vault root.
    pub total_file_count: usize,
    /// Number of files containing the Engram generated marker.
    pub generated_file_count: usize,
    /// Number of files not marked as Engram generated files.
    pub user_file_count: usize,
    /// Memory items currently eligible for compilation.
    pub memory_item_count: usize,
    /// Knowledge commits currently eligible for compilation.
    pub knowledge_commit_count: usize,
    /// Repositories currently eligible for compilation.
    pub repository_count: usize,
    /// Entities currently eligible for compilation.
    pub entity_count: usize,
    /// Projects currently eligible for compilation.
    pub project_count: usize,
    /// Files expected from compiling the current store snapshot.
    pub expected_generated_file_count: usize,
}

/// A vault page read from disk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryVaultPage {
    /// Vault root path.
    pub root: String,
    /// Page path relative to root.
    pub relative_path: String,
    /// Absolute page path.
    pub absolute_path: String,
    /// Whether the page contains the Engram generated marker.
    pub generated: bool,
    /// Page contents.
    pub contents: String,
}

/// Repository topology data included in the vault export.
#[derive(Debug, Clone)]
pub struct RepositoryVaultSnapshot {
    /// Canonical repository.
    pub repository: GitRepository,
    /// Known local checkouts for this repository.
    pub checkouts: Vec<LocalCheckout>,
    /// Registered monorepo components.
    pub components: Vec<MonorepoComponent>,
    /// Project links for the repository.
    pub project_links: Vec<ProjectRepositoryLink>,
}

/// Write a deterministic Markdown vault projection.
pub(crate) fn write_memory_vault(
    root: &Path,
    items: &[MemoryItem],
    commits: &[KnowledgeCommit],
    repositories: &[RepositoryVaultSnapshot],
) -> IndexResult<MemoryVaultExport> {
    fs::create_dir_all(root)?;

    let mut export = MemoryVaultExport {
        root: root.display().to_string(),
        files_written: Vec::new(),
        files_skipped: Vec::new(),
        memory_item_count: items.len(),
        knowledge_commit_count: commits.len(),
        repository_count: repositories.len(),
        entity_count: 0,
        project_count: 0,
    };

    let mut sorted_items = items.to_vec();
    sorted_items.sort_by(|left, right| {
        left.updated_at
            .cmp(&right.updated_at)
            .then_with(|| left.title.cmp(&right.title))
            .then_with(|| left.id.to_string().cmp(&right.id.to_string()))
    });

    let mut sorted_commits = commits.to_vec();
    sorted_commits.sort_by(|left, right| {
        left.created_at
            .cmp(&right.created_at)
            .then_with(|| left.id.to_string().cmp(&right.id.to_string()))
    });

    let mut sorted_repositories = repositories.to_vec();
    sorted_repositories.sort_by(|left, right| {
        left.repository
            .name
            .cmp(&right.repository.name)
            .then_with(|| {
                left.repository
                    .id
                    .to_string()
                    .cmp(&right.repository.id.to_string())
            })
    });

    let entity_names = entity_names(&sorted_items);
    let entity_paths = unique_named_paths(&entity_names, "entities");
    export.entity_count = entity_names.len();

    let project_names = project_names(&sorted_items, &sorted_repositories);
    let project_paths = unique_named_paths(&project_names, "projects");
    export.project_count = project_names.len();

    write_generated_file(
        root,
        Path::new("99_System").join("Vault-Index.md"),
        &vault_index(
            &sorted_items,
            &sorted_commits,
            &sorted_repositories,
            &entity_names,
            &entity_paths,
            &project_names,
            &project_paths,
        ),
        &mut export,
    )?;
    write_generated_file(
        root,
        Path::new("memory").join("index.md"),
        &memory_index(&sorted_items, &sorted_commits),
        &mut export,
    )?;

    for item in &sorted_items {
        write_generated_file(
            root,
            item_relative_path(item),
            &memory_item_page(item),
            &mut export,
        )?;
    }

    for commit in &sorted_commits {
        write_generated_file(
            root,
            commit_relative_path(commit),
            &knowledge_commit_page(commit),
            &mut export,
        )?;
    }

    write_generated_file(
        root,
        Path::new("entities").join("index.md"),
        &entities_index(&entity_names, &entity_paths),
        &mut export,
    )?;
    for entity_name in &entity_names {
        let relative_path = entity_paths.get(entity_name).ok_or_else(|| {
            IndexError::InvalidState(format!("missing vault path for entity: {entity_name}"))
        })?;
        write_generated_file(
            root,
            relative_path.clone(),
            &entity_page(entity_name, &sorted_items),
            &mut export,
        )?;
    }

    write_generated_file(
        root,
        Path::new("repositories").join("index.md"),
        &repositories_index(&sorted_repositories),
        &mut export,
    )?;
    for repository in &sorted_repositories {
        write_generated_file(
            root,
            repository_relative_path(&repository.repository),
            &repository_page(repository),
            &mut export,
        )?;
    }

    for project_name in &project_names {
        let relative_path = project_paths.get(project_name).ok_or_else(|| {
            IndexError::InvalidState(format!("missing vault path for project: {project_name}"))
        })?;
        write_generated_file(
            root,
            relative_path.clone(),
            &project_page(project_name, &sorted_items, &sorted_repositories),
            &mut export,
        )?;
    }

    export.files_written.sort();
    export.files_skipped.sort();
    Ok(export)
}

/// Create the Memory OS vault directory skeleton.
pub(crate) fn init_memory_vault(root: &Path) -> IndexResult<MemoryVaultInit> {
    fs::create_dir_all(root)?;

    let mut init = MemoryVaultInit {
        root: root.display().to_string(),
        directories_created: Vec::new(),
        directories_existing: Vec::new(),
    };

    for directory in VAULT_DIRECTORIES {
        let path = root.join(directory);
        if path.is_dir() {
            init.directories_existing.push((*directory).to_string());
        } else {
            fs::create_dir_all(&path)?;
            init.directories_created.push((*directory).to_string());
        }
    }

    Ok(init)
}

/// Inspect the current vault state without writing any files.
pub(crate) fn inspect_memory_vault(
    root: &Path,
    items: &[MemoryItem],
    commits: &[KnowledgeCommit],
    repositories: &[RepositoryVaultSnapshot],
) -> IndexResult<MemoryVaultStatus> {
    let exists = root.exists();
    let mut missing_directories = Vec::new();
    for directory in VAULT_DIRECTORIES {
        if !root.join(directory).is_dir() {
            missing_directories.push((*directory).to_string());
        }
    }

    let (total_file_count, generated_file_count, user_file_count) = if exists {
        count_vault_files(root)?
    } else {
        (0, 0, 0)
    };
    let entity_count = entity_names(items).len();
    let project_count = project_names(items, repositories).len();
    let expected_generated_file_count = expected_vault_file_count(
        items.len(),
        commits.len(),
        repositories.len(),
        entity_count,
        project_count,
    );

    Ok(MemoryVaultStatus {
        root: root.display().to_string(),
        exists,
        initialized: exists && missing_directories.is_empty(),
        missing_directories,
        total_file_count,
        generated_file_count,
        user_file_count,
        memory_item_count: items.len(),
        knowledge_commit_count: commits.len(),
        repository_count: repositories.len(),
        entity_count,
        project_count,
        expected_generated_file_count,
    })
}

/// Read a page from the vault. The page path must stay inside the vault root.
pub(crate) fn read_memory_vault_page(
    root: &Path,
    page: &str,
) -> IndexResult<Option<MemoryVaultPage>> {
    let mut relative_path = normalize_vault_relative_path(page)?;
    if relative_path.extension().is_none() {
        relative_path.set_extension("md");
    }

    let path = root.join(&relative_path);
    if !path.exists() {
        return Ok(None);
    }
    if !path.is_file() {
        return Err(IndexError::InvalidState(format!(
            "vault page is not a file: {}",
            path.display()
        )));
    }

    let contents = fs::read_to_string(&path)?;
    let generated = contents.contains(GENERATED_MARKER);
    Ok(Some(MemoryVaultPage {
        root: root.display().to_string(),
        relative_path: path_to_markdown(&relative_path),
        absolute_path: path.display().to_string(),
        generated,
        contents,
    }))
}

fn vault_index(
    items: &[MemoryItem],
    commits: &[KnowledgeCommit],
    repositories: &[RepositoryVaultSnapshot],
    entity_names: &BTreeSet<String>,
    entity_paths: &BTreeMap<String, PathBuf>,
    project_names: &BTreeSet<String>,
    project_paths: &BTreeMap<String, PathBuf>,
) -> String {
    let mut output = frontmatter("vault_index", Vec::new());
    output.push_str("# Engram Memory Vault\n\n");
    output.push_str("## Summary\n\n");
    output.push_str(&format!("- Memory items: {}\n", items.len()));
    output.push_str(&format!("- Knowledge commits: {}\n", commits.len()));
    output.push_str(&format!("- Repositories: {}\n", repositories.len()));
    output.push_str(&format!("- Entities: {}\n", entity_names.len()));
    output.push_str(&format!("- Projects: {}\n\n", project_names.len()));

    output.push_str("## Entry Points\n\n");
    output.push_str("- [Memory](../memory/index.md)\n");
    output.push_str("- [Entities](../entities/index.md)\n");
    output.push_str("- [Repositories](../repositories/index.md)\n");
    if !entity_names.is_empty() {
        output.push_str("- Entities\n");
        for entity_name in entity_names {
            if let Some(path) = entity_paths.get(entity_name) {
                output.push_str(&format!(
                    "  - [{}](../{})\n",
                    escape_link_text(entity_name),
                    path_to_markdown(path)
                ));
            }
        }
    }
    if !project_names.is_empty() {
        output.push_str("- Projects\n");
        for project_name in project_names {
            if let Some(path) = project_paths.get(project_name) {
                output.push_str(&format!(
                    "  - [{}](../{})\n",
                    escape_link_text(project_name),
                    path_to_markdown(path)
                ));
            }
        }
    }
    output
}

fn memory_index(items: &[MemoryItem], commits: &[KnowledgeCommit]) -> String {
    let mut output = frontmatter("memory_index", Vec::new());
    output.push_str("# Memory\n\n");
    output.push_str("## Status Counts\n\n");
    for (status, count) in status_counts(items) {
        output.push_str(&format!("- {}: {}\n", status, count));
    }

    output.push_str("\n## Items\n\n");
    for item in items {
        output.push_str(&format!(
            "- [{}](items/{}) - {} - {}\n",
            escape_link_text(&item.title),
            file_name(&item_relative_path(item)),
            item.kind,
            item.status
        ));
    }

    output.push_str("\n## Knowledge Commits\n\n");
    for commit in commits {
        output.push_str(&format!(
            "- [{}](commits/{}) - {} change(s)\n",
            escape_link_text(&commit.message),
            file_name(&commit_relative_path(commit)),
            commit.change_count()
        ));
    }
    output
}

fn memory_item_page(item: &MemoryItem) -> String {
    let mut fields = vec![
        ("engram_id".to_string(), yaml_string(&item.id.to_string())),
        ("kind".to_string(), yaml_string(&item.kind.to_string())),
        ("status".to_string(), yaml_string(&item.status.to_string())),
        (
            "scope_type".to_string(),
            yaml_string(memory_scope_type(&item.scope)),
        ),
        (
            "scope".to_string(),
            yaml_string(&memory_scope_label(&item.scope)),
        ),
        (
            "origin".to_string(),
            yaml_string(&claim_origin_label(&item.origin)),
        ),
        (
            "confidence".to_string(),
            format!("{:.3}", item.confidence.value()),
        ),
        (
            "writer_harness".to_string(),
            yaml_string(&item.writer.harness.to_string()),
        ),
        (
            "writer_model_provider".to_string(),
            yaml_string(&item.writer.model.provider),
        ),
        (
            "writer_model".to_string(),
            yaml_string(&item.writer.model.model),
        ),
        (
            "created_at".to_string(),
            yaml_string(&format_time(item.created_at)),
        ),
        (
            "updated_at".to_string(),
            yaml_string(&format_time(item.updated_at)),
        ),
    ];
    push_optional_field(
        &mut fields,
        "writer_surface",
        item.writer.surface.as_deref(),
    );
    push_optional_field(
        &mut fields,
        "writer_model_version",
        item.writer.model.version.as_deref(),
    );
    if let Some(review_after) = item.review_after {
        fields.push((
            "review_after".to_string(),
            yaml_string(&format_time(review_after)),
        ));
    }

    let mut output = frontmatter("memory_item", fields);
    output.push_str(&format!("# {}\n\n", item.title));
    output.push_str(&item.content);
    output.push_str("\n\n## Metadata\n\n");
    output.push_str(&format!("- Kind: {}\n", item.kind));
    output.push_str(&format!("- Status: {}\n", item.status));
    output.push_str(&format!("- Scope: {}\n", memory_scope_label(&item.scope)));
    output.push_str(&format!("- Origin: {}\n", claim_origin_label(&item.origin)));
    output.push_str(&format!("- Confidence: {:.3}\n", item.confidence.value()));
    output.push_str(&format!(
        "- Writer: {} / {} / {}\n",
        item.writer.harness, item.writer.model.provider, item.writer.model.model
    ));
    if !item.tags.is_empty() {
        output.push_str(&format!("- Tags: {}\n", item.tags.join(", ")));
    }
    if !item.supersedes.is_empty() {
        output.push_str("- Supersedes:\n");
        for id in &item.supersedes {
            output.push_str(&format!("  - {}\n", id));
        }
    }

    output.push_str("\n## Evidence\n\n");
    if item.evidence.is_empty() {
        output.push_str("No evidence recorded.\n");
    } else {
        for evidence in &item.evidence {
            output.push_str(&format!(
                "- {}: {}",
                evidence_kind_label(&evidence.kind),
                evidence.target
            ));
            if let Some(summary) = &evidence.summary {
                output.push_str(&format!(" - {}", summary));
            }
            output.push('\n');
            if let Some(excerpt) = &evidence.excerpt {
                output.push_str(&format!("  - Excerpt: {}\n", excerpt));
            }
        }
    }

    output
}

fn knowledge_commit_page(commit: &KnowledgeCommit) -> String {
    let fields = vec![
        ("engram_id".to_string(), yaml_string(&commit.id.to_string())),
        ("message".to_string(), yaml_string(&commit.message)),
        (
            "writer_harness".to_string(),
            yaml_string(&commit.writer.harness.to_string()),
        ),
        (
            "writer_model".to_string(),
            yaml_string(&commit.writer.model.model),
        ),
        (
            "created_at".to_string(),
            yaml_string(&format_time(commit.created_at)),
        ),
    ];

    let mut output = frontmatter("knowledge_commit", fields);
    output.push_str(&format!("# {}\n\n", commit.message));
    output.push_str("## Commit\n\n");
    output.push_str(&format!("- ID: {}\n", commit.id));
    if let Some(parent_id) = commit.parent_id {
        output.push_str(&format!("- Parent: {}\n", parent_id));
    }
    if let Some(session_id) = commit.session_id {
        output.push_str(&format!("- Session: {}\n", session_id));
    }
    output.push_str(&format!(
        "- Writer: {} / {} / {}\n",
        commit.writer.harness, commit.writer.model.provider, commit.writer.model.model
    ));

    output.push_str("\n## Changes\n\n");
    if commit.changes.is_empty() {
        output.push_str("No changes recorded.\n");
    } else {
        for change in &commit.changes {
            output.push_str(&format!(
                "- {}: {} - {}\n",
                memory_change_type_label(change.change_type),
                change.title,
                change.summary
            ));
            if let Some(item_id) = change.item_id {
                output.push_str(&format!("  - Item: {}\n", item_id));
            }
            if change.before_hash.is_some() || change.after_hash.is_some() {
                output.push_str(&format!(
                    "  - Hash: {} -> {}\n",
                    change.before_hash.as_deref().unwrap_or("unknown"),
                    change.after_hash.as_deref().unwrap_or("unknown")
                ));
            }
        }
    }
    output
}

fn repositories_index(repositories: &[RepositoryVaultSnapshot]) -> String {
    let mut output = frontmatter("repositories_index", Vec::new());
    output.push_str("# Repositories\n\n");
    if repositories.is_empty() {
        output.push_str("No repositories registered.\n");
    } else {
        for snapshot in repositories {
            output.push_str(&format!(
                "- [{}]({})",
                escape_link_text(&snapshot.repository.name),
                file_name(&repository_relative_path(&snapshot.repository))
            ));
            if let Some(remote_url) = &snapshot.repository.remote_url {
                output.push_str(&format!(" - {}", remote_url));
            }
            output.push('\n');
        }
    }
    output
}

fn entities_index(
    entity_names: &BTreeSet<String>,
    entity_paths: &BTreeMap<String, PathBuf>,
) -> String {
    let mut output = frontmatter("entities_index", Vec::new());
    output.push_str("# Entities\n\n");
    if entity_names.is_empty() {
        output.push_str("No entity-scoped memory items exported.\n");
    } else {
        for entity_name in entity_names {
            if let Some(path) = entity_paths.get(entity_name) {
                output.push_str(&format!(
                    "- [{}]({})\n",
                    escape_link_text(entity_name),
                    path_to_markdown_without_prefix(path, "entities")
                ));
            }
        }
    }
    output
}

fn entity_page(entity_name: &str, items: &[MemoryItem]) -> String {
    let fields = vec![("entity_name".to_string(), yaml_string(entity_name))];
    let mut output = frontmatter("entity", fields);
    output.push_str(&format!("# Entity: {}\n\n", entity_name));

    output.push_str("## Memory Items\n\n");
    let entity_items: Vec<_> = items
        .iter()
        .filter(|item| memory_scope_entity_name(&item.scope) == Some(entity_name))
        .collect();
    if entity_items.is_empty() {
        output.push_str("No entity-scoped memory items exported.\n");
    } else {
        for item in entity_items {
            output.push_str(&format!(
                "- [{}](../../{}) - {} - {}\n",
                escape_link_text(&item.title),
                path_to_markdown(&item_relative_path(item)),
                item.kind,
                item.status
            ));
        }
    }

    output
}

fn repository_page(snapshot: &RepositoryVaultSnapshot) -> String {
    let repository = &snapshot.repository;
    let fields = vec![
        (
            "engram_id".to_string(),
            yaml_string(&repository.id.to_string()),
        ),
        ("repository_name".to_string(), yaml_string(&repository.name)),
        (
            "provider".to_string(),
            yaml_string(&repository.provider.to_string()),
        ),
    ];
    let mut output = frontmatter("repository", fields);
    output.push_str(&format!("# Repository: {}\n\n", repository.name));

    output.push_str("## Source\n\n");
    output.push_str(&format!("- ID: {}\n", repository.id));
    output.push_str(&format!("- Provider: {}\n", repository.provider));
    if let Some(remote_url) = &repository.remote_url {
        output.push_str(&format!("- Remote: {}\n", remote_url));
    }
    if let Some(default_branch) = &repository.default_branch {
        output.push_str(&format!("- Default branch: {}\n", default_branch));
    }
    if let Some(description) = &repository.description {
        output.push_str(&format!("- Description: {}\n", description));
    }

    output.push_str("\n## Local Checkouts\n\n");
    if snapshot.checkouts.is_empty() {
        output.push_str("No local checkouts registered.\n");
    } else {
        for checkout in &snapshot.checkouts {
            output.push_str(&format!("- {}\n", checkout.local_path));
            if let Some(branch) = &checkout.current_branch {
                output.push_str(&format!("  - Branch: {}\n", branch));
            }
            if let Some(head_sha) = &checkout.head_sha {
                output.push_str(&format!("  - HEAD: {}\n", head_sha));
            }
            if let Some(is_dirty) = checkout.is_dirty {
                output.push_str(&format!("  - Dirty: {}\n", is_dirty));
            }
        }
    }

    output.push_str("\n## Project Links\n\n");
    if snapshot.project_links.is_empty() {
        output.push_str("No project links registered.\n");
    } else {
        for link in &snapshot.project_links {
            output.push_str(&format!("- {} ({})", link.project_name, link.role));
            if let Some(component_path) = &link.component_path {
                output.push_str(&format!(" - component: {}", component_path));
            }
            output.push('\n');
        }
    }

    output.push_str("\n## Components\n\n");
    if snapshot.components.is_empty() {
        output.push_str("No monorepo components registered.\n");
    } else {
        for component in &snapshot.components {
            output.push_str(&format!("- {} ({})", component.name, component.path));
            if let Some(kind) = &component.kind {
                output.push_str(&format!(" - {}", kind));
            }
            if let Some(description) = &component.description {
                output.push_str(&format!(" - {}", description));
            }
            output.push('\n');
        }
    }

    output
}

fn project_page(
    project_name: &str,
    items: &[MemoryItem],
    repositories: &[RepositoryVaultSnapshot],
) -> String {
    let fields = vec![("project_name".to_string(), yaml_string(project_name))];
    let mut output = frontmatter("project", fields);
    output.push_str(&format!("# Project: {}\n\n", project_name));

    output.push_str("## Memory Items\n\n");
    let project_items: Vec<_> = items
        .iter()
        .filter(|item| memory_scope_project_name(&item.scope) == Some(project_name))
        .collect();
    if project_items.is_empty() {
        output.push_str("No project-scoped memory items exported.\n");
    } else {
        for item in project_items {
            output.push_str(&format!(
                "- [{}](../../{}) - {} - {}\n",
                escape_link_text(&item.title),
                path_to_markdown(&item_relative_path(item)),
                item.kind,
                item.status
            ));
        }
    }

    output.push_str("\n## Repositories\n\n");
    let mut wrote_repository = false;
    for snapshot in repositories {
        let links: Vec<_> = snapshot
            .project_links
            .iter()
            .filter(|link| link.project_name.eq_ignore_ascii_case(project_name))
            .collect();
        if links.is_empty() {
            continue;
        }
        wrote_repository = true;
        output.push_str(&format!(
            "- [{}](../../{})\n",
            escape_link_text(&snapshot.repository.name),
            path_to_markdown(&repository_relative_path(&snapshot.repository))
        ));
        for link in links {
            output.push_str(&format!("  - Role: {}", link.role));
            if let Some(component_path) = &link.component_path {
                output.push_str(&format!("; component: {}", component_path));
            }
            output.push('\n');
        }
    }
    if !wrote_repository {
        output.push_str("No repositories linked to this project.\n");
    }

    output
}

fn status_counts(items: &[MemoryItem]) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for item in items {
        *counts.entry(item.status.to_string()).or_insert(0) += 1;
    }
    counts
}

fn project_names(
    items: &[MemoryItem],
    repositories: &[RepositoryVaultSnapshot],
) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in items {
        if let Some(project_name) = memory_scope_project_name(&item.scope) {
            names.insert(project_name.to_string());
        }
    }
    for snapshot in repositories {
        for link in &snapshot.project_links {
            names.insert(link.project_name.clone());
        }
    }
    names
}

fn entity_names(items: &[MemoryItem]) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in items {
        if let Some(entity_name) = memory_scope_entity_name(&item.scope) {
            names.insert(entity_name.to_string());
        }
    }
    names
}

fn memory_scope_project_name(scope: &MemoryScope) -> Option<&str> {
    match scope {
        MemoryScope::Project { project_name, .. } => Some(project_name.as_str()),
        MemoryScope::Task { project_name, .. } => project_name.as_deref(),
        _ => None,
    }
}

fn memory_scope_entity_name(scope: &MemoryScope) -> Option<&str> {
    match scope {
        MemoryScope::Entity { entity_name, .. } => Some(entity_name.as_str()),
        _ => None,
    }
}

fn memory_scope_type(scope: &MemoryScope) -> &'static str {
    match scope {
        MemoryScope::Global => "global",
        MemoryScope::User => "user",
        MemoryScope::Project { .. } => "project",
        MemoryScope::Task { .. } => "task",
        MemoryScope::Entity { .. } => "entity",
        MemoryScope::Repository { .. } => "repository",
        MemoryScope::Session { .. } => "session",
        MemoryScope::Custom { .. } => "custom",
    }
}

fn memory_scope_label(scope: &MemoryScope) -> String {
    match scope {
        MemoryScope::Global => "global".to_string(),
        MemoryScope::User => "user".to_string(),
        MemoryScope::Project { project_name, .. } => format!("project:{project_name}"),
        MemoryScope::Task {
            project_name,
            task_name,
            ..
        } => project_name
            .as_ref()
            .map(|project| format!("task:{project}/{task_name}"))
            .unwrap_or_else(|| format!("task:{task_name}")),
        MemoryScope::Entity { entity_name, .. } => format!("entity:{entity_name}"),
        MemoryScope::Repository {
            repository_id,
            remote_url,
            local_path,
        } => repository_id
            .map(|id| format!("repository:{id}"))
            .or_else(|| remote_url.as_ref().map(|url| format!("repository:{url}")))
            .or_else(|| local_path.as_ref().map(|path| format!("repository:{path}")))
            .unwrap_or_else(|| "repository".to_string()),
        MemoryScope::Session { session_id } => format!("session:{session_id}"),
        MemoryScope::Custom { name } => format!("custom:{name}"),
    }
}

fn claim_origin_label(origin: &ClaimOrigin) -> String {
    match origin {
        ClaimOrigin::UserStated => "user_stated".to_string(),
        ClaimOrigin::UserCorrected => "user_corrected".to_string(),
        ClaimOrigin::AgentObserved => "agent_observed".to_string(),
        ClaimOrigin::AgentInferred => "agent_inferred".to_string(),
        ClaimOrigin::ToolResult => "tool_result".to_string(),
        ClaimOrigin::Imported => "imported".to_string(),
        ClaimOrigin::Migrated => "migrated".to_string(),
        ClaimOrigin::GeneratedSummary => "generated_summary".to_string(),
        ClaimOrigin::Custom(value) => value.clone(),
    }
}

fn evidence_kind_label(kind: &EvidenceKind) -> String {
    match kind {
        EvidenceKind::SessionEvent => "session_event".to_string(),
        EvidenceKind::ToolCall => "tool_call".to_string(),
        EvidenceKind::File => "file".to_string(),
        EvidenceKind::GitCommit => "git_commit".to_string(),
        EvidenceKind::Url => "url".to_string(),
        EvidenceKind::Document => "document".to_string(),
        EvidenceKind::Observation => "observation".to_string(),
        EvidenceKind::ManualReview => "manual_review".to_string(),
        EvidenceKind::Custom(value) => value.clone(),
    }
}

fn memory_change_type_label(change_type: MemoryChangeType) -> &'static str {
    match change_type {
        MemoryChangeType::Added => "added",
        MemoryChangeType::Updated => "updated",
        MemoryChangeType::Superseded => "superseded",
        MemoryChangeType::Archived => "archived",
        MemoryChangeType::Rejected => "rejected",
        MemoryChangeType::Linked => "linked",
        MemoryChangeType::Unlinked => "unlinked",
    }
}

fn frontmatter(page_type: &str, fields: Vec<(String, String)>) -> String {
    let mut output = String::new();
    output.push_str("---\n");
    output.push_str(&format!("generated_by: {}\n", yaml_string(GENERATED_BY)));
    output.push_str(&format!("page_type: {}\n", yaml_string(page_type)));
    for (key, value) in fields {
        output.push_str(&format!("{key}: {value}\n"));
    }
    output.push_str("---\n\n");
    output.push_str(GENERATED_MARKER);
    output.push_str("\n\n");
    output
}

fn push_optional_field(fields: &mut Vec<(String, String)>, key: &str, value: Option<&str>) {
    if let Some(value) = value {
        fields.push((key.to_string(), yaml_string(value)));
    }
}

fn write_generated_file(
    root: &Path,
    relative_path: PathBuf,
    contents: &str,
    export: &mut MemoryVaultExport,
) -> IndexResult<()> {
    let path = root.join(&relative_path);
    if path.exists() {
        let existing = fs::read(&path)?;
        if !String::from_utf8_lossy(&existing).contains(GENERATED_MARKER) {
            export.files_skipped.push(path_to_markdown(&relative_path));
            return Ok(());
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, contents)?;
    export.files_written.push(path_to_markdown(&relative_path));
    Ok(())
}

fn expected_vault_file_count(
    memory_item_count: usize,
    knowledge_commit_count: usize,
    repository_count: usize,
    entity_count: usize,
    project_count: usize,
) -> usize {
    let system_index = 1;
    let memory_index = 1;
    let entity_index = 1;
    let repository_index = 1;
    system_index
        + memory_index
        + memory_item_count
        + knowledge_commit_count
        + entity_index
        + entity_count
        + repository_index
        + repository_count
        + project_count
}

fn count_vault_files(root: &Path) -> IndexResult<(usize, usize, usize)> {
    fn visit(path: &Path, total: &mut usize, generated: &mut usize) -> IndexResult<()> {
        for entry in fs::read_dir(path)? {
            let entry = entry?;
            let file_type = entry.file_type()?;
            let path = entry.path();
            if file_type.is_dir() {
                visit(&path, total, generated)?;
            } else if file_type.is_file() {
                *total += 1;
                let contents = fs::read(&path)?;
                if String::from_utf8_lossy(&contents).contains(GENERATED_MARKER) {
                    *generated += 1;
                }
            }
        }
        Ok(())
    }

    let mut total = 0;
    let mut generated = 0;
    visit(root, &mut total, &mut generated)?;
    Ok((total, generated, total.saturating_sub(generated)))
}

fn normalize_vault_relative_path(value: &str) -> IndexResult<PathBuf> {
    let trimmed = value.trim().trim_start_matches('/');
    if trimmed.is_empty() {
        return Err(IndexError::InvalidState(
            "vault page path must not be empty".to_string(),
        ));
    }

    let mut normalized = PathBuf::new();
    for component in Path::new(trimmed).components() {
        match component {
            Component::Normal(part) => normalized.push(part),
            Component::CurDir => {}
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(IndexError::InvalidState(
                    "vault page path must be relative and stay inside the vault".to_string(),
                ));
            }
        }
    }

    if normalized.as_os_str().is_empty() {
        Err(IndexError::InvalidState(
            "vault page path must not be empty".to_string(),
        ))
    } else {
        Ok(normalized)
    }
}

fn item_relative_path(item: &MemoryItem) -> PathBuf {
    Path::new("memory")
        .join("items")
        .join(format!("{}-{}.md", item.id, slugify(&item.title)))
}

fn commit_relative_path(commit: &KnowledgeCommit) -> PathBuf {
    Path::new("memory").join("commits").join(format!(
        "{}-{}.md",
        commit.id,
        slugify(&commit.message)
    ))
}

fn repository_relative_path(repository: &GitRepository) -> PathBuf {
    Path::new("repositories").join(format!(
        "{}-{}.md",
        slugify(&repository.name),
        repository.id
    ))
}

fn unique_named_paths(names: &BTreeSet<String>, base_dir: &str) -> BTreeMap<String, PathBuf> {
    let mut slug_groups: BTreeMap<String, Vec<&String>> = BTreeMap::new();
    for name in names {
        slug_groups.entry(slugify(name)).or_default().push(name);
    }

    let mut paths = BTreeMap::new();
    for (slug, names_for_slug) in slug_groups {
        let canonical_name = names_for_slug
            .iter()
            .copied()
            .find(|name| name.as_str() == slug)
            .or_else(|| names_for_slug.first().copied());

        for name in names_for_slug {
            let directory_name = if Some(name) == canonical_name {
                slug.clone()
            } else {
                format!("{}-{}", slug, stable_suffix(name))
            };
            paths.insert(
                name.clone(),
                Path::new(base_dir).join(directory_name).join("index.md"),
            );
        }
    }

    paths
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_string()
}

fn path_to_markdown(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn path_to_markdown_without_prefix(path: &Path, prefix: &str) -> String {
    path.strip_prefix(prefix)
        .map(path_to_markdown)
        .unwrap_or_else(|_| path_to_markdown(path))
}

fn slugify(value: &str) -> String {
    let mut slug = String::new();
    let mut previous_dash = false;
    for ch in value.chars().flat_map(char::to_lowercase) {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            slug.push(ch);
            previous_dash = false;
        } else if !previous_dash {
            slug.push('-');
            previous_dash = true;
        }
        if slug.len() >= 80 {
            break;
        }
    }

    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "untitled".to_string()
    } else {
        slug
    }
}

fn stable_suffix(value: &str) -> String {
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{:08x}", hash as u32)
}

fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

fn escape_link_text(value: &str) -> String {
    value.replace('\\', "\\\\").replace(']', "\\]")
}

fn format_time(value: OffsetDateTime) -> String {
    value
        .format(&time::format_description::well_known::Rfc3339)
        .expect("RFC3339 timestamp formatting should succeed")
}

#[cfg(test)]
mod tests {
    use super::*;
    use engram_core::memory::{
        ClaimOrigin, EvidenceRef, Harness, KnowledgeCommit, MemoryChange, MemoryChangeType,
        MemoryKind, ModelIdentity, WriterProvenance,
    };
    use engram_core::repository::{ProjectRepositoryRole, RepositoryProvider};
    use tempfile::tempdir;

    fn writer() -> WriterProvenance {
        WriterProvenance::agent(Harness::Codex, ModelIdentity::new("openai", "gpt-5.5"))
            .with_surface("desktop")
    }

    fn memory_item(title: &str) -> MemoryItem {
        memory_item_with_scope(title, MemoryScope::project("engram"))
    }

    fn memory_item_with_scope(title: &str, scope: MemoryScope) -> MemoryItem {
        MemoryItem::new(
            MemoryKind::Decision,
            title,
            "Use a deterministic Markdown projection for Memory OS.",
            scope,
            ClaimOrigin::UserStated,
            writer(),
        )
        .with_evidence(EvidenceRef::new(EvidenceKind::ManualReview, "vault-test"))
        .with_tag("memory-os")
    }

    #[test]
    fn write_memory_vault_creates_generated_pages() {
        let dir = tempdir().unwrap();
        let item = memory_item("Write vault pages");
        let commit = KnowledgeCommit::new(writer(), "Capture vault export").with_change(
            MemoryChange::new(
                MemoryChangeType::Added,
                "Write vault pages",
                "Added vault page export.",
            )
            .with_item(item.id),
        );
        let repository = GitRepository::new("engram")
            .with_remote_url("git@github.com:ymeiri/engram.git")
            .with_provider(RepositoryProvider::GitHub);
        let link =
            ProjectRepositoryLink::new("engram", repository.id, ProjectRepositoryRole::Primary);
        let snapshot = RepositoryVaultSnapshot {
            repository,
            checkouts: Vec::new(),
            components: Vec::new(),
            project_links: vec![link],
        };

        let export = write_memory_vault(
            dir.path(),
            std::slice::from_ref(&item),
            &[commit],
            &[snapshot],
        )
        .unwrap();

        assert_eq!(export.memory_item_count, 1);
        assert_eq!(export.knowledge_commit_count, 1);
        assert_eq!(export.repository_count, 1);
        assert_eq!(export.entity_count, 0);
        assert_eq!(export.project_count, 1);
        assert!(export.files_skipped.is_empty());
        assert!(export
            .files_written
            .iter()
            .any(|path| path.starts_with("memory/items/")));
        assert!(dir.path().join("memory/index.md").exists());

        let item_path = dir.path().join(item_relative_path(&item));
        let item_page = fs::read_to_string(item_path).unwrap();
        assert!(item_page.contains(GENERATED_MARKER));
        assert!(item_page.contains("generated_by: \"engram-memory-os\""));
        assert!(item_page.contains("# Write vault pages"));
        assert!(item_page.contains("manual_review: vault-test"));
    }

    #[test]
    fn write_memory_vault_skips_user_owned_files() {
        let dir = tempdir().unwrap();
        let index_path = dir.path().join("memory/index.md");
        fs::create_dir_all(index_path.parent().unwrap()).unwrap();
        fs::write(&index_path, "# User owned\n").unwrap();

        let export = write_memory_vault(dir.path(), &[], &[], &[]).unwrap();

        assert!(export
            .files_skipped
            .contains(&"memory/index.md".to_string()));
        let index = fs::read_to_string(index_path).unwrap();
        assert_eq!(index, "# User owned\n");
    }

    #[test]
    fn init_and_status_report_vault_skeleton() {
        let dir = tempdir().unwrap();
        let init = init_memory_vault(dir.path()).unwrap();

        assert_eq!(init.root, dir.path().display().to_string());
        assert!(init
            .directories_created
            .contains(&"memory/items".to_string()));
        assert!(dir.path().join("entities").is_dir());
        assert!(dir.path().join("repositories").is_dir());

        let status = inspect_memory_vault(dir.path(), &[], &[], &[]).unwrap();
        assert!(status.exists);
        assert!(status.initialized);
        assert_eq!(status.generated_file_count, 0);
        assert_eq!(status.user_file_count, 0);
        assert_eq!(status.expected_generated_file_count, 4);
    }

    #[test]
    fn status_counts_generated_and_user_files() {
        let dir = tempdir().unwrap();
        init_memory_vault(dir.path()).unwrap();
        let item = memory_item("Status counts generated files");
        write_memory_vault(dir.path(), std::slice::from_ref(&item), &[], &[]).unwrap();
        fs::write(dir.path().join("notes.md"), "# User note\n").unwrap();

        let status = inspect_memory_vault(dir.path(), &[item], &[], &[]).unwrap();

        assert!(status.initialized);
        assert_eq!(status.user_file_count, 1);
        assert_eq!(status.memory_item_count, 1);
        assert_eq!(
            status.generated_file_count,
            status.expected_generated_file_count
        );
    }

    #[test]
    fn write_memory_vault_uses_unique_project_paths_for_slug_collisions() {
        let dir = tempdir().unwrap();
        let items = vec![
            memory_item_with_scope("Lowercase project", MemoryScope::project("engram")),
            memory_item_with_scope("Titlecase project", MemoryScope::project("Engram")),
        ];

        let export = write_memory_vault(dir.path(), &items, &[], &[]).unwrap();

        assert_eq!(export.project_count, 2);
        let project_paths: BTreeSet<_> = export
            .files_written
            .iter()
            .filter(|path| path.starts_with("projects/") && path.ends_with("/index.md"))
            .collect();
        assert_eq!(project_paths.len(), 2);
        assert!(project_paths.contains(&"projects/engram/index.md".to_string()));

        let status = inspect_memory_vault(dir.path(), &items, &[], &[]).unwrap();
        assert_eq!(
            status.generated_file_count,
            status.expected_generated_file_count
        );
    }

    #[test]
    fn write_memory_vault_creates_entity_index_and_pages() {
        let dir = tempdir().unwrap();
        let item = memory_item_with_scope(
            "Review all system operational rule",
            MemoryScope::entity("review-all-system"),
        );

        let export = write_memory_vault(dir.path(), std::slice::from_ref(&item), &[], &[]).unwrap();

        assert_eq!(export.entity_count, 1);
        assert!(dir.path().join("entities/index.md").exists());
        assert!(dir
            .path()
            .join("entities/review-all-system/index.md")
            .exists());

        let index = fs::read_to_string(dir.path().join("entities/index.md")).unwrap();
        assert!(index.contains("[review-all-system](review-all-system/index.md)"));

        let page =
            fs::read_to_string(dir.path().join("entities/review-all-system/index.md")).unwrap();
        assert!(page.contains("entity_name: \"review-all-system\""));
        assert!(page.contains("Review all system operational rule"));
    }

    #[test]
    fn read_memory_vault_page_reads_relative_page_and_rejects_escape() {
        let dir = tempdir().unwrap();
        let item = memory_item("Read vault page");
        write_memory_vault(dir.path(), std::slice::from_ref(&item), &[], &[]).unwrap();

        let page = read_memory_vault_page(dir.path(), "memory/index")
            .unwrap()
            .unwrap();
        assert_eq!(page.relative_path, "memory/index.md");
        assert!(page.generated);
        assert!(page.contents.contains("Read vault page"));

        let err = read_memory_vault_page(dir.path(), "../outside")
            .expect_err("parent directory traversal should be rejected");
        assert!(err.to_string().contains("stay inside the vault"));
    }
}
